# Generated by Django 4.2 on 2023-05-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_email_profile_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.CharField(default='NAN', max_length=100),
        ),
    ]
