# Generated by Django 4.2 on 2023-05-04 11:11

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('caption', models.TextField()),
                ('image', models.ImageField(upload_to='post_images')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('num_of_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
