# Generated by Django 4.2 on 2023-05-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_followers_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='follower',
            field=models.CharField(default='NAN', max_length=100),
        ),
        migrations.AddField(
            model_name='following',
            name='following',
            field=models.CharField(default='NAN', max_length=100),
        ),
    ]
